version: '3.9'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "🔹 Initializing Airflow Database..."
        airflow db init
        echo "✅ Database initialized!"
        airflow users create \
          --username airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com \
          --password airflow || true
        echo "✅ Default user created (or already exists)."
    volumes:
      - ./Data_Pipeline/dags:/opt/airflow/dags
      - ./Data_Pipeline:/opt/airflow/Data_Pipeline
      - ./logs:/opt/airflow/logs

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False

      # ✅ Email (SMTP) settings for alerts
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.office365.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=ashokumar.g@northeastern.edu
      - AIRFLOW__SMTP__SMTP_PASSWORD=${EMAIL_PASSWORD}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=ashokumar.g@northeastern.edu

    ports:
      - "8081:8080"
    command: webserver
    volumes:
      - ./Data_Pipeline/dags:/opt/airflow/dags
      - ./Data_Pipeline:/opt/airflow/Data_Pipeline
      - ./logs:/opt/airflow/logs

  scheduler:
    build: .
    restart: always
    depends_on:
      - airflow-init
      - webserver
      - postgres
    command: scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

      # ✅ Email (SMTP) settings for alerts
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.office365.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=ashokumar.g@northeastern.edu
      - AIRFLOW__SMTP__SMTP_PASSWORD=${EMAIL_PASSWORD}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=ashokumar.g@northeastern.edu

    volumes:
      - ./Data_Pipeline/dags:/opt/airflow/dags
      - ./Data_Pipeline:/opt/airflow/Data_Pipeline
      - ./logs:/opt/airflow/logs

  triggerer:
    build: .
    restart: always
    depends_on:
      - scheduler
    command: triggerer
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow

      # ✅ Email (SMTP) settings for alerts
      - AIRFLOW__EMAIL__EMAIL_BACKEND=airflow.utils.email.send_email_smtp
      - AIRFLOW__SMTP__SMTP_HOST=smtp.office365.com
      - AIRFLOW__SMTP__SMTP_STARTTLS=True
      - AIRFLOW__SMTP__SMTP_SSL=False
      - AIRFLOW__SMTP__SMTP_PORT=587
      - AIRFLOW__SMTP__SMTP_USER=ashokumar.g@northeastern.edu
      - AIRFLOW__SMTP__SMTP_PASSWORD=${EMAIL_PASSWORD}
      - AIRFLOW__SMTP__SMTP_MAIL_FROM=ashokumar.g@northeastern.edu

    volumes:
      - ./Data_Pipeline/dags:/opt/airflow/dags
      - ./Data_Pipeline:/opt/airflow/Data_Pipeline
      - ./logs:/opt/airflow/logs

volumes:
  postgres-db-volume: