stages:
  fetch_routes:
    cmd: python Data_Pipeline/scripts/fetch_all_routes.py
    deps:
      - Data_Pipeline/scripts/fetch_all_routes.py
    outs:
      - Data_Pipeline/data/all_routes.json
      - Data_Pipeline/data/all_routes.yaml

  fetch:
    cmd: python Data_Pipeline/scripts/fetch_data.py
    deps:
      - Data_Pipeline/scripts/fetch_data.py
      - Data_Pipeline/data/all_routes.yaml
      - params.yaml
    outs:
      - Data_Pipeline/data/raw

  preprocess:
    cmd: python Data_Pipeline/scripts/preprocess_data.py
    deps:
      - Data_Pipeline/scripts/preprocess_data.py
      - Data_Pipeline/data/raw
      - params.yaml
    outs:
      - Data_Pipeline/data/processed/predictions.csv
      - Data_Pipeline/data/processed/vehicles.csv
      - Data_Pipeline/data/processed/alerts.csv

  validate:
    cmd: python Data_Pipeline/scripts/validate_schema.py
    deps:
      - Data_Pipeline/scripts/validate_schema.py
      - Data_Pipeline/data/processed/predictions.csv
      - Data_Pipeline/data/processed/vehicles.csv
      - Data_Pipeline/data/processed/alerts.csv
      - params.yaml
    outs:
      - Data_Pipeline/data/validation/schema_validation_report.json

  anomalies:
    cmd: python Data_Pipeline/scripts/detect_anomalies.py
    deps:
      - Data_Pipeline/scripts/detect_anomalies.py
      - Data_Pipeline/data/processed/predictions.csv
      - Data_Pipeline/data/processed/vehicles.csv
      - Data_Pipeline/data/processed/alerts.csv
      - params.yaml
    outs:
      - Data_Pipeline/data/validation/anomaly_report.json

  schema_stats:
    cmd: python Data_Pipeline/scripts/validate_schema_profile.py
    deps:
      - Data_Pipeline/scripts/validate_schema_profile.py
      - Data_Pipeline/data/processed/predictions.csv
      - Data_Pipeline/data/processed/vehicles.csv
      - Data_Pipeline/data/processed/alerts.csv
      - params.yaml
    outs:
      - Data_Pipeline/data/validation/profiling_schema_report.json

  bias_detection:
    cmd: python Data_Pipeline/scripts/detect_bias.py
    deps:
      - Data_Pipeline/scripts/detect_bias.py
      - Data_Pipeline/data/processed/predictions.csv
    outs:
      - Data_Pipeline/data/validation/bias_report.csv